apiVersion: v1
kind: Service
metadata:
  name: tasklist-service
  namespace: tasklist
spec:
  selector:
    app: tasklist-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
