apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasklist-ingress
  namespace: tasklist
spec:
  rules:
  - host: tasklist.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tasklist-app
            port:
              number: 8080
