name: CD - Deploy to VM

on:
  workflow_run:
    workflows: ["CI - Build, Test & Run"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: [self-hosted, Linux]

    # Run only when CI succeeded OR manually triggered
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ==========================
      #      CACHE DEPENDENCIES
      # ==========================
      - name: Cache Python venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('ansible/requirements.txt') }}

      - name: Create and activate venv (if missing)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          # Create and activate virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Upgrade pip inside venv
          pip install --upgrade pip

          # Install Ansible + Docker module
          pip install "ansible>=8.6,<9" docker

      - name: Activate venv (cached)
        if: steps.cache-venv.outputs.cache-hit == 'true'
        run: |
          source venv/bin/activate
          pip --version

      # Cache Ansible Galaxy
      - name: Cache Ansible Galaxy
        id: cache-galaxy
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: galaxy-${{ runner.os }}-community-docker

      - name: Install Ansible Galaxy Collections
        if: steps.cache-galaxy.outputs.cache-hit != 'true'
        run: |
          source venv/bin/activate
          ansible-galaxy collection install community.docker

      # ==========================
      #       DEPLOY TO VM
      # ==========================
      - name: Create Inventory
        run: |
          mkdir -p ansible
          echo "[appservers]" > ansible/inventory
          echo "172.19.19.10 ansible_user=sisonke ansible_ssh_private_key_file=/home/sisonke/.ssh/id_ed25519" >> ansible/inventory

      - name: Deploy Application
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        run: |
          source venv/bin/activate
          ansible-playbook -i ansible/inventory ansible/deploy.yml \
            --extra-vars "registry=${REGISTRY} image_name=${IMAGE_NAME} image_tag=${IMAGE_TAG}"

