name: CD - Deploy to VM

on:
  workflow_run:
    workflows: ["CI - Build, Test & Run"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: [self-hosted, Linux]

    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    steps:
      - uses: actions/checkout@v4

      # Cache Python venv
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('ansible/requirements.txt') }}

      - name: Install dependencies
        run: |
          python3 -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r ansible/requirements.txt

      # Cache galaxy
      - name: Cache Galaxy
        id: cache-galaxy
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: galaxy-${{ runner.os }}-${{ hashFiles('ansible/collections.yml') }}

      - name: Install Ansible Collections
        if: steps.cache-galaxy.outputs.cache-hit != 'true'
        run: |
          ./venv/bin/ansible-galaxy install -r ansible/collections.yml

      # Inventory
      - name: Create inventory file
        run: |
          echo "[appservers]" > inventory.ini
          echo "172.19.19.10 ansible_user=sisonke ansible_ssh_private_key_file=/home/sisonke/.ssh/id_ed25519" >> inventory.ini

      # Deploy
      - name: Deploy App
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        run: |
          ./venv/bin/ansible-playbook -i inventory.ini ansible/deploy.yml \
            --extra-vars "registry=${REGISTRY} image_name=${IMAGE_NAME} image_tag=${IMAGE_TAG}"

