name: CD - Deploy to VM

on:
  workflow_run:
    workflows: ["CI - Build, Test & Run"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-vm:
    runs-on: [self-hosted, Linux]

    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')

    steps:
      # ----------------------
      # Checkout Code
      # ----------------------
      - uses: actions/checkout@v4

      # ----------------------
      # Set up Python
      # ----------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'  # automatic pip caching

      # ----------------------
      # Install Dependencies
      # ----------------------
      - name: Install Ansible & Docker SDK
        run: |
          pip install --upgrade pip --no-input
          pip install "ansible>=8.6,<9" docker --no-input

      # ----------------------
      # Install Ansible Galaxy Collections
      # ----------------------
      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install community.docker --force

      # ----------------------
      # Create Inventory
      # ----------------------
      - name: Create inventory file
        run: |
          echo "[appservers]" > inventory.ini
          echo "172.19.19.10 ansible_user=sisonke ansible_ssh_private_key_file=/home/sisonke/.ssh/id_ed25519" >> inventory.ini

      # ----------------------
      # Deploy Application
      # ----------------------
      - name: Deploy App
        env:
          REGISTRY: ${{ secrets.REGISTRY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        run: |
          ansible-playbook -i inventory.ini ansible/deploy.yml \
            --extra-vars "registry=${REGISTRY} image_name=${IMAGE_NAME} image_tag=${IMAGE_TAG}"
